### ISSUE TITLE
Requires h5 file extension. Should allow hdf5 extension as well?

### ISSUE THREAD

**Issue by ahalota** [HDFGroup/h5serv#79]
Unless I'm missing some difference between the two file types, it would be nice to accept hdf5 as an extension as well. Right now I'm renaming my files so that they get picked up by the server, can't seem to find where in the code that happens.

**Comment by jreadey** [comment]
There's a config value here: https://github.com/HDFGroup/h5serv/blob/develop/server/config.py, "hdf5_ext", that you can change if a different extension would be better.  The main purpose of it was to filter out HDF5 files in the data directory from everything else, so the server would have a quick way to know what should be made visible.  

Would it be useful if this config value was a list rather than a string?  Then it could be setup to support a number of common extensions.

**Comment by ahalota** [comment]
Perfect, I forgot about the config file. I haven't had a need for multiple file types, but yes, I can see that coming up in some cases.
